# Generated by Django 5.0.2 on 2024-06-28 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10, unique=True)),
                ('profile_picture', models.ImageField(default='member_pictures/default.jpeg', upload_to='member_pictures')),
                ('position', models.CharField(choices=[('S', 'student'), ('E', 'employee'), ('T', 'teacher'), ('P', 'personnel')], default='P', max_length=10)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'members',
            },
        ),
    ]
