# Generated by Django 5.0.2 on 2024-06-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('student', 'student'), ('employee', 'employee'), ('teacher', 'teacher'), ('personnel', 'personnel'), ('admin', 'admin')], default='P', max_length=10),
        ),
    ]
